import { Achievment } from "../types/achievmentType";

export const MOCK_ACHIEVMENTS: Achievment[] = [
  {
    id: 1,
    title: "Первый код",
    description: 'Написать свою первую программу "Hello World"',
    icon: "👨‍💻",
    reward: 50,
    unlocked: false,
    progress: 100,
    category: "Кодинг",
    rarity: "Обычная",
  },
  {
    id: 2,
    title: "Git Мастер",
    description: "Сделать 100 коммитов в репозиторий",
    icon: "📚",
    reward: 100,
    unlocked: false,
    progress: 100,
    category: "Инструменты",
    rarity: "Обычная",
  },
  {
    id: 3,
    title: "React Инициация",
    description: "Создать первый React компонент",
    icon: "⚛️",
    reward: 150,
    unlocked: false,
    progress: 70,
    category: "Фреймворки",
    rarity: "Необычная",
  },
  {
    id: 4,
    title: "TypeScript Гуру",
    description: "Написать 1000 строк типобезопасного кода",
    icon: "🔷",
    reward: 200,
    unlocked: false,
    progress: 45,
    category: "Языки",
    rarity: "Редкая",
  },
  {
    id: 5,
    title: "База Данных",
    description: "Настроить и подключить первую базу данных",
    icon: "🗄️",
    reward: 180,
    unlocked: false,
    progress: 0,
    category: "BackEnd",
    rarity: "Необычная",
  },
  {
    id: 6,
    title: "Деплой Герой",
    description: "Задеплоить приложение на продакшен",
    icon: "🚀",
    reward: 250,
    unlocked: false,
    progress: 20,
    category: "DevOps",
    rarity: "Редкое",
  },
  {
    id: 7,
    title: "Code Review Профи",
    description: "Провести 10 код-ревью",
    icon: "👁️",
    reward: 120,
    unlocked: false,
    progress: 30,
    category: "Командная",
    rarity: "Обычное",
  },
  {
    id: 8,
    title: "Тестирование",
    description: "Достичь 80% покрытия кода тестами",
    icon: "🧪",
    reward: 220,
    unlocked: false,
    progress: 10,
    category: "Тестирование",
    rarity: "Редкое",
  },
  {
    id: 9,
    title: "Оптимизатор",
    description: "Ускорить приложение на 50%",
    icon: "⚡",
    reward: 300,
    unlocked: false,
    progress: 5,
    category: "Ускорение",
    rarity: "Эпическое",
  },
  {
    id: 10,
    title: "Ментор",
    description: "Помочь 5 начинающим разработчикам",
    icon: "🧠",
    reward: 280,
    unlocked: false,
    progress: 100,
    category: "Сообщество",
    rarity: "Эпическое",
  },
  {
    id: 11,
    title: "Open Source",
    description: "Сделать вклад в open-source проект",
    icon: "🌐",
    reward: 350,
    unlocked: false,
    progress: 0,
    category: "Сообщество",
    rarity: "Легендарное",
  },
  {
    id: 12,
    title: "Архитектор",
    description: "Спроектировать архитектуру приложения",
    icon: "🏗️",
    reward: 400,
    unlocked: false,
    progress: 15,
    category: "Архитектура",
    rarity: "Легендарное",
  },
] as const