import { ShopType } from "../types/shopType";

export const MOCK_SHOP: ShopType[] = [
  {
    id: 1,
    title: 'JavaScript Ускорение',
    description: 'Повышает уровень JavaScript на 1',
    type: 'Скилл',
    category: 'Hard',
    price: 100,
    currency: 'DNA',
    icon: '🟨',
    effect: {
      type: 'skill-up',
      value: 1,
    },
    rarity: 'Обычное',
    maxPurchases: 3,
  },
  {
    id: 2,
    title: 'TypeScript Гуру',
    description: 'Повышает уровень TypeScript на 2',
    type: 'Скилл',
    category: 'Hard',
    price: 250,
    currency: 'DNA',
    icon: '🔷',
    effect: {
      type: 'skill-up',
      value: 2,
    },
    rarity: 'Редкое',
    requiredLevel: 3,
    maxPurchases: 2,
  },
  {
    id: 3,
    title: 'React Мастер',
    description: 'Повышает уровень React на 3',
    type: 'Скилл',
    category: 'Hard',
    price: 500,
    currency: 'DNA',
    icon: '⚛️',
    effect: {
      type: 'skill-up',
      value: 3,
    },
    rarity: 'Эпическое',
    requiredLevel: 5,
    maxPurchases: 1,
  },
  {
    id: 4,
    title: 'Node.js Эксперт',
    description: 'Открывает навык Node.js или повышает на 2',
    type: 'Скилл',
    category: 'Hard',
    price: 400,
    currency: 'DNA',
    icon: '📡',
    effect: {
      type: 'skill-up',
      value: 2,
    },
    rarity: 'Редкое',
    requiredLevel: 4,
  },
  {
    id: 5,
    title: 'Базы данных',
    description: 'Повышает навыки работы с базами данных',
    type: 'Скилл',
    category: 'Hard',
    price: 300,
    currency: 'DNA',
    icon: '🗄️',
    effect: {
      type: 'skill-up',
      value: 1,
    },
    rarity: 'Обычное',
  },

  // Soft Skills
  {
    id: 6,
    title: 'Коммуникабельность',
    description: 'Увеличивает уровень общительности на 2',
    type: 'Скилл',
    category: 'Soft',
    price: 150,
    currency: 'DNA',
    icon: '💬',
    effect: {
      type: 'skill-up',
      value: 2,
    },
    rarity: 'Обычное',
    maxPurchases: 4,
  },
  {
    id: 7,
    title: 'Лидерство',
    description: 'Повышает навыки руководства и ответственности',
    type: 'Скилл',
    category: 'Soft',
    price: 350,
    currency: 'DNA',
    icon: '👑',
    effect: {
      type: 'skill-up',
      value: 2,
    },
    rarity: 'Редкое',
    requiredLevel: 3,
  },
  {
    id: 8,
    title: 'Тайм-менеджмент',
    description: 'Улучшает навыки управления временем',
    type: 'Скилл',
    category: 'Soft',
    price: 200,
    currency: 'DNA',
    icon: '⏰',
    effect: {
      type: 'skill-up',
      value: 1,
    },
    rarity: 'Обычное',
  },
  {
    id: 9,
    title: 'Креативное мышление',
    description: 'Развивает креативность и нестандартное мышление',
    type: 'Скилл',
    category: 'Soft',
    price: 280,
    currency: 'DNA',
    icon: '💡',
    effect: {
      type: 'skill-up',
      value: 2,
    },
    rarity: 'Редкое',
  },

  // Бусты
  {
    id: 10,
    title: 'XP Буст',
    description: '+50% к получаемому опыту на 4 часа',
    type: 'Буст',
    category: 'Hard',
    price: 80,
    currency: 'DNA',
    icon: '⚡',
    effect: {
      type: 'xp-boost',
      value: 1.5,
    },
    rarity: 'Обычное',
  },
  {
    id: 11,
    title: 'Супер XP Буст',
    description: '+100% к получаемому опыту на 2 часа',
    type: 'Буст',
    category: 'Hard',
    price: 150,
    currency: 'DNA',
    icon: '🚀',
    effect: {
      type: 'xp-boost',
      value: 2.0,
    },
    rarity: 'Редкое',
  },
  {
    id: 12,
    title: 'Ускорение обучения',
    description: 'Время выполнения миссий сокращается на 30% на 6 часов',
    type: 'Буст',
    category: 'Hard',
    price: 120,
    currency: 'DNA',
    icon: '🎯',
    effect: {
      type: 'time-reduce',
      value: 0.7,
    },
    rarity: 'Обычное',
  },

  // Специальные предложения
  {
    id: 13,
    title: 'Набор Junior Developer',
    description: 'Комплексное повышение всех Hard навыков на 1',
    type: 'Особенный',
    category: 'Hard',
    price: 800,
    currency: 'DNA',
    icon: '🎁',
    effect: {
      type: 'skill-up',
      value: 1,
    },
    rarity: 'Эпическое',
    maxPurchases: 1,
  },
  {
    id: 14,
    title: 'Набор Team Lead',
    description: 'Комплексное повышение всех Soft навыков на 2',
    type: 'Особенный',
    category: 'Soft',
    price: 1000,
    currency: 'DNA',
    icon: '🌟',
    effect: {
      type: 'skill-up',
      value: 2,
    },
    rarity: 'Легендарное',
    requiredLevel: 8,
    maxPurchases: 1,
  },
  {
    id: 15,
    title: 'Легендарный FullStack',
    description: 'Открывает все Hard навыки или повышает на 3',
    type: 'Особенный',
    category: 'Hard',
    price: 2000,
    currency: 'DNA',
    icon: '🏆',
    effect: {
      type: 'skill-up',
      value: 3,
    },
    rarity: 'legendary',
    requiredLevel: 10,
    maxPurchases: 1,
  },
] as const;